Fix/build warnings 2024 09 15
michaelsakharov/Prowl pull request #159
Opened 2024-09-16 18:21 UTC by brmassa

Attacking #158

fixes for:

CS0108: 4
CS4014: 4
CS9191: 3
CS8619: 3
CS0649: 3
CS8765: 2
CS8767: 2
CS8620: 2
CS0659: 1
CS0661: 1
CS8714: 1
CS8607: 1
CS8509: 1
CS1998: 1

2024-09-16 19:46 UTC, brmassa commented
CS8629 and some other fixes

2024-09-16 20:36 UTC, brmassa commented
CS8603 and some CS8601

down to 406 warnings

2024-09-17 00:33 UTC, brmassa commented
down to 361 warnings

2024-09-18 12:30 UTC, michaelsakharov commented
It might make more sense to disable the Readonly warning.
As there's a ton of cases with the Readonly's where it doesn't make a whole lot of sense.
Including a lot of public API intended for end users to change in runtime

2024-09-19 01:43 UTC, michaelsakharov commented
The issue with switching to Properties is that moves away from the Unity API. Unity doesn't really even support properties-only fields, our serializer also doesn't handle them properly and it would be a reasonably big change for newcomers to c# who only know c# through Unity.

I think the read-only one makes sense to remove for the time being, What do you think @sinnwrig

2024-09-19 02:18 UTC, PaperPrototype commented
hehe yeah im one of those unity C# only people :P

2024-09-19 02:19 UTC, PaperPrototype commented
One thought I have is maybe not worrying about Unity only devs? We would only be perpetuating the problem.

2024-09-19 02:41 UTC, brmassa commented
It's problem going to bite us in the future, but for the time being, I'm reverting it. There are still a lot (200+) other warning to attack.

2024-09-19 02:42 UTC, michaelsakharov commented
> One thought I have is maybe not worrying about Unity only devs? We would only be perpetuating the problem.

I mean a huge part of prowl is to be a unity alternative, so it's main audience by far will be unity devs. On top of the fact that it's not really a problem to perpetuate in the first place. Its less a problem and more a design choice.

2024-09-19 02:52 UTC, brmassa commented
ok. Commit reverted.

I believe Unity did some choices back in old days due lack of resources. Joachim repeatedly said there are several design mistakes that now they kinda have to live with.

Their serializer is sub-par. Sirenix (Odin) serializer is much more capable.

Using public mutable fields is a very bad practice. Basically all Static Analyzers will complain: Visual Studio, Rider, Codacy, Qodana, etc.

Sicne drag-and-drop replacement is virtually impossible, I believe we could have peace of mind on taking some things in other direction. As long it's well documented and explained to users.

2024-09-19 05:20 UTC, sinnwrig commented
> The issue with switching to Properties is that moves away from the Unity API. Unity doesn't really even support properties-only fields, our serializer also doesn't handle them properly and it would be a reasonably big change for newcomers to c# who only know c# through Unity.
> 
> I think the read-only one makes sense to remove for the time being, What do you think @sinnwrig

The readonly warnings should only be appearing because of C# style recommendations, correct? If so, it would probably be feasible to revert the warnings back to suggestions in the .editorconfig, since the compiler can't be aware of how a user and the serializer might interact with it. On top of that, the warning seems a bit like premature optimization, since the performance boost gained by setting fields to readonly is negligible in most cases unless it's in perf. critical code, in which case it can be optimized manually later down the line.

2024-09-19 05:24 UTC, michaelsakharov requested changes

2024-09-19 05:29 UTC, sinnwrig commented
> ok. Commit reverted.
> 
> I believe Unity did some choices back in old days due lack of resources. Joachim (Unity ttech chief back then) repeatedly said there are several design mistakes that now they kinda have to live with.
> 
> Their serializer is sub-par. Sirenix (Odin) serializer is much more capable.
> 
> Using public mutable fields is a very bad practice. Basically all Static Analyzers will complain: Visual Studio, Rider, Codacy, Qodana, etc.
> 
> Sicne drag-and-drop replacement is virtually impossible, I believe we could have peace of mind on taking some things in other direction. As long it's well documented and explained to users.

On the public mutable fields, it seems a bit harsh to remove them completely because of bad design practice, since for many cases, having simple, raw, exposed values without a get/set (even if it's auto-implemented) is useful. Worst-case, the [field:SerializeField] attribute can be used to let the serializer get to an auto-implemented property.

2026-04-27 11:53 UTC, closed without merging